### ISSUE TITLE
Stacktrace is lost

### ISSUE THREAD

**Issue by agsha** [vojtajina/node-mocks#6]
why is the stack trace being overwritten [here](https://github.com/vojtajina/node-mocks/commit/da578fd4d08be9b1514e5e2987261bd627bd4d85#L0R107)?

This is losing all the stacktrace information

**Comment by vojtajina** [comment]
I think this was broken in older Node and so you would get the line number of the `vm.runInNewContext` call (which is in node-mocks and therefore is not helpful at all.

I tried it with latest 0.10.13 and it works fine, so we should just remove the whole try catch...
